# Generated by Django 5.0.4 on 2024-05-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('dp', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
