# Generated by Django 5.0.4 on 2024-05-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.FloatField(max_length=20)),
                ('check_out', models.FloatField(max_length=20)),
                ('error_rate', models.FloatField()),
                ('submission_status', models.BooleanField(default=False)),
            ],
        ),
    ]
