# Generated by Django 5.0.4 on 2024-05-07 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='empno',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.employee'),
        ),
    ]
