# Generated by Django 5.0.4 on 2024-05-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_metric_empno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='check_in',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='metric',
            name='check_out',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='metric',
            name='error_rate',
            field=models.CharField(max_length=20),
        ),
    ]
