# Generated by Django 5.0.4 on 2024-05-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_metric_check_in_alter_metric_check_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='error_rate',
            field=models.FloatField(),
        ),
    ]
